const allowedTargets = new Set([
  // Intentionally Vulnerable Test Hosts
  'scanme.nmap.org',
  '45.33.32.156',
  'testphp.vulnweb.com',
  '44.228.249.3', // Covers testphp, testasp, testaspnet, testhtml5
  'testasp.vulnweb.com',
  'testaspnet.vulnweb.com',
  'testhtml5.vulnweb.com',
  'demo.testfire.net',
  '65.61.137.117',
  'zero.webappsecurity.com',
  '54.82.22.214',
  'juice-shop.herokuapp.com',
  '46.137.15.86',

  // Bug Bounty Program Scope Domains
  'google.com',
  'youtube.com',
  'facebook.com',
  'instagram.com',
  'microsoft.com',
  'apple.com',
  'tesla.com',
  'shopify.com',
  'github.com',
  'hackerone.com',
  'bugcrowd.com',
  'uber.com',
  'wordpress.org',
  'mozilla.org',
  'dropbox.com',
  'paypal.com',
  'twitter.com',
  'slack.com',
  'medium.com',
  'pinterest.com',
  'stackoverflow.com',
  'atlassian.com',
  'zoom.us',
  'tumblr.com',
  'trello.com',
  'linkedin.com',
  'reddit.com',
  'cloudflare.com',
  'digitalocean.com',
  'stripe.com',
  'squareup.com',
  'bitbucket.org',
  'gitlab.com',
  'jetbrains.com',
  'telegram.org',
  'signal.org',
  'protonmail.com',
  'heroku.com',
  'aws.amazon.com',
  'oracle.com',
  'intel.com',
  'snapchat.com'
]);

module.exports = allowedTargets; 